# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: API CI

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'Feature/**'
      - 'fix/*'
      - 'Fix/*'
    paths: 
      - 'api/src/**'

jobs:
  test:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api
        
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn -f pom.xml test
